create-assets:
	/bin/bash create_assets

run-builder:
	flutter packages pub run build_runner build --delete-conflicting-outputs && find . -name "*.inject.summary" |xargs rm -- && find . -name "*.inject.dart" -size 0 |xargs rm --

clean-project:
	find . -name "*.inject.summary" |xargs rm --
	find . -name "*.inject.dart" -size 0 |xargs rm --
	find . -name "*.reflectable.dart" |xargs rm --
